Exception on /delete/3/2 [GET]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/JLPT_Registration_Form/app.py", line 532, in delete_row
    write_deleted_log(deleted_info, deleted_row)
  File "/home/debian/JLPT_Registration_Form/config.py", line 83, in write_deleted_log
    with open(file_path, 'a') as f:
PermissionError: [Errno 13] Permission denied: 'files/deleted_info_N3.csv'
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 143, in confirm
    with open(f"files/registered_data_N{form_data['jlpt_level']}.csv", 'a') as f:
PermissionError: [Errno 13] Permission denied: 'files/registered_data_N2.csv'
Exception on /confirm/2/1 [GET]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/JLPT_Registration_Form/app.py", line 584, in confirm_candidate
    with open(confirmed_data_file, 'a', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'files/Confirmed/confirmed_data_N2.csv'
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/JLPT_Registration_Form/app.py", line 369, in dashboard
    return render_template('dashboard.html', data=get_jlpt_counter(), data_2=get_jlpt_confirmed_counter(), data_3=get_jlpt_special_need_confirmed_count(), data_4=get_jlpt_special_need_count())
  File "/home/debian/JLPT_Registration_Form/config.py", line 16, in get_jlpt_confirmed_counter
    jlpt_confirmed_counter[level] = int(last_row[4])
IndexError: list index out of range
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/JLPT_Registration_Form/app.py", line 369, in dashboard
    return render_template('dashboard.html', data=get_jlpt_counter(), data_2=get_jlpt_confirmed_counter(), data_3=get_jlpt_special_need_confirmed_count(), data_4=get_jlpt_special_need_count())
  File "/home/debian/JLPT_Registration_Form/config.py", line 16, in get_jlpt_confirmed_counter
    jlpt_confirmed_counter[level] = int(last_row[4])
IndexError: list index out of range
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/JLPT_Registration_Form/app.py", line 369, in dashboard
    return render_template('dashboard.html', data=get_jlpt_counter(), data_2=get_jlpt_confirmed_counter(), data_3=get_jlpt_special_need_confirmed_count(), data_4=get_jlpt_special_need_count())
  File "/home/debian/JLPT_Registration_Form/config.py", line 16, in get_jlpt_confirmed_counter
    jlpt_confirmed_counter[level] = int(last_row[4])
IndexError: list index out of range
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/JLPT_Registration_Form/app.py", line 369, in dashboard
    return render_template('dashboard.html', data=get_jlpt_counter(), data_2=get_jlpt_confirmed_counter(), data_3=get_jlpt_special_need_confirmed_count(), data_4=get_jlpt_special_need_count())
  File "/home/debian/JLPT_Registration_Form/config.py", line 16, in get_jlpt_confirmed_counter
    jlpt_confirmed_counter[level] = int(last_row[4])
IndexError: list index out of range
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/JLPT_Registration_Form/app.py", line 369, in dashboard
    return render_template('dashboard.html', data=get_jlpt_counter(), data_2=get_jlpt_confirmed_counter(), data_3=get_jlpt_special_need_confirmed_count(), data_4=get_jlpt_special_need_count())
  File "/home/debian/JLPT_Registration_Form/config.py", line 16, in get_jlpt_confirmed_counter
    jlpt_confirmed_counter[level] = int(last_row[4])
IndexError: list index out of range
Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/debian/JLPT_Registration_Form/app.py", line 369, in dashboard
    return render_template('dashboard.html', data=get_jlpt_counter(), data_2=get_jlpt_confirmed_counter(), data_3=get_jlpt_special_need_confirmed_count(), data_4=get_jlpt_special_need_count())
  File "/home/debian/JLPT_Registration_Form/config.py", line 16, in get_jlpt_confirmed_counter
    jlpt_confirmed_counter[level] = int(last_row[4])
IndexError: list index out of range
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 140, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /registration [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 115, in registration
    print(f"dob is : {dob}")
NameError: name 'dob' is not defined
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
Exception on /confirm [POST]
Traceback (most recent call last):
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/debian/JLPT_Registration_Form/.venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/debian/JLPT_Registration_Form/app.py", line 141, in confirm
    dob_day, dob_month, dob_year = form_data['dob'].split('-')
ValueError: not enough values to unpack (expected 3, got 1)
